global:
  css:
    base:
      # css/root.css: { weight: -200 }
      css/base/base.css: {}
      css/base/image.css: {}
      css/base/list.css: {}
      css/base/nav.css: {}
      css/base/table.css: {}
    layout:
      css/layout/layout.css: {}
      css/layout/layout-admin.css: {}
    theme:
      css/theme/eleven.css: { weight: -20}
      css/theme/typography.css: {}
    component:
      css/component/icon.css: {}
  js:
    js/eleven.js: {}
  dependencies:
    - system/admin
    - core/modernizr

# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
# shortcut:
#   css:
#     theme:
      # templates/shortcut/shortcut.css: {}

# jquery_ui:
#   css:
#     theme:
      # templates/jquery_ui/jquery_ui.css: {}


card:
  css:
    theme:
      templates/layout-landing/card.css: {weight: -20}


# ------------------------------------------------------------------------------
# System
# ------------------------------------------------------------------------------
messages:
  css:
    theme:
      templates/component/messages/messages.css: {}


# ------------------------------------------------------------------------------
# Admin landing pages
# ------------------------------------------------------------------------------
admin.config:
  css:
    theme:
      templates/layout-landing/config/admin-config.css: {}

views:
  css:
    theme:
      templates/layout-landing/views/structure-table-views.css: {}
      templates/layout-landing/views/views-admin.css: {}
      
# ------------------------------------------------------------------------------
# navigation
# ------------------------------------------------------------------------------
nav.breadcrumb:
  css:
    theme:
      templates/component/navigation/breadcrumb/breadcrumb.css: {}

nav.tabs:
  css:
    theme:
      templates/component/navigation/tabs.css: {}
      templates/component/navigation/localtask/localtask.css: {}
      templates/component/navigation/localtask/localtask-icons.css: {}

# ------------------------------------------------------------------------------
# Forms
# ------------------------------------------------------------------------------
form.form:
  css:
    theme:
      templates/component/form/form.css: {}
      templates/component/form/button/form-button.css: {}

      templates/component/form/details/form-details.css: {}
      templates/component/form/fieldset/form-fieldset.css: {}
      templates/component/form/textarea/form-textarea.css: {}
      templates/component/form/input/form-input.css: {}
      templates/component/form/input/form-input-submit.css: {}
      templates/component/form/checkbox/form-checkbox.css: {}
      templates/component/form/radio/form-radio.css: {}
      templates/component/form/select/form-select.css: {}

form.file:
  css:
    theme:
      templates/component/form/input-file/form-input-file.css: {}
  js:
    templates/component/form/input-file/form-input-file.js: {}


button.action:
  css:
    theme:
      templates/component/button-action/button-action.css: {}
# ------------------------------------------------------------------------------
# Modules
# ------------------------------------------------------------------------------
modules:
  css:
    theme:
      templates/layout-landing/modules/modules.css: {}
      templates/layout-landing/modules/modules-icons.css: {}

themes:
  css:
    theme:
      templates/layout-landing/themes/themes.css: {}
